### ISSUE TITLE
misleading build steps in readme

### ISSUE THREAD

**Issue by ajohanssonwalder** [JaffSoft/swagger-style-validator#1]
Hi there,

Just reading the instructions and I had a bit of trouble.
https://github.com/JaffSoft/swagger-style-validator#to-build

I could not get `gradlew assemble` to generate the mentioned jar file, and then execute the run commands. 
Here are the steps I used to get it working. Perhaps the readme could be updated?

Following the Readme, no jar produced:
```
$ chmod +x gradlew
$ ./gradlew assemble

:modules/lib:compileJava
:modules/lib:processResources NO-SOURCE
:modules/lib:classes
:modules/lib:jar
:modules/cli:compileJava
:modules/cli:processResources NO-SOURCE
:modules/cli:classes
:modules/cli:jar
:modules/cli:assemble
:modules/lib:assemble

BUILD SUCCESSFUL
```

Jar produced in the following manner:

To Build
```
gradle build
gradle fatJar
```

To Run
`java -jar modules/cli/build/libs/swagger-style-validator-cli-1.0.jar -s specs/petstore.yaml -o specs/options.json`

**Comment by JFCote** [comment]
Hi @ajohanssonwalder !

Thanks for the report. You are right, the `README.md` could use a little bit of love. I've done the whole project in approximately a week in my spare time and didn't have to come back to fix small stuff.

I'm seeing a pull request from you, will check that today! Thanks you very much for your interest in my little project :)

**Comment by JFCote** [comment]
Fixed by PR: https://github.com/JaffSoft/swagger-style-validator/pull/2
